// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EditorMarkdown: typeof import('./../src/components/editor/markdown.vue')['default']
    EditorWangEditor: typeof import('./../src/components/editor/wangEditor.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    FormButton: typeof import('./../src/components/form/button.vue')['default']
    FormError: typeof import('./../src/components/form/error.vue')['default']
    FormInput: typeof import('./../src/components/form/input.vue')['default']
    FormVeeValidateError: typeof import('./../src/components/form/veeValidateError.vue')['default']
    HdAnimateList: typeof import('./../src/components/hd/animateList.vue')['default']
    HdBreadcrumb: typeof import('./../src/components/hd/breadcrumb.vue')['default']
    HdCaptcha: typeof import('./../src/components/hd/captcha.vue')['default']
    HdCode: typeof import('./../src/components/hd/code.vue')['default']
    HdNotification: typeof import('./../src/components/hd/notification.vue')['default']
  }
}

export { }
