// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EditorMarkdown: typeof import('./../src/components/editor/markdown.vue')['default']
    EditorWangEditor: typeof import('./../src/components/editor/wangEditor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FormButton: typeof import('./../src/components/form/button.vue')['default']
    FormError: typeof import('./../src/components/form/error.vue')['default']
    FormInput: typeof import('./../src/components/form/input.vue')['default']
    FormVeeValidateError: typeof import('./../src/components/form/veeValidateError.vue')['default']
    HdAnimateList: typeof import('./../src/components/hd/animateList.vue')['default']
    HdBreadcrumb: typeof import('./../src/components/hd/breadcrumb.vue')['default']
    HdCaptcha: typeof import('./../src/components/hd/captcha.vue')['default']
    HdCode: typeof import('./../src/components/hd/code.vue')['default']
    HdNotification: typeof import('./../src/components/hd/notification.vue')['default']
  }
}

export { }
